:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2023-09-23 Sat 11:56>
:MODIFIED: <2023-09-23 Sat 11:56>
:TYPE: blog
:END:
#+title: Emacs' Buffers Stop Drawing
#+filetags: :emacs:

I'm having this really weird problem at the moment with my [[../emacs][emacs config]]
resulting in buffers not redrawing. It isn't immediate, as in I can be working
for a while and everything is fine, but then eventually it will cease to redraw
buffers when they update. I can get them to redraw with I /do/ something, such as
type or click my mouse, but they won't update until that point. I first thought
it was only non-file buffers, however I have found that even buffers tied to
files are not redrawing. When it does happen the only way to solve the prolbem
is to close emacs and start again.

I have a suspicion that it might be tied to memory use, because it seems that
running long-winded terminal commands (such as ~yarn install~) make the problem
happen more quickly. Perhaps my GC isn't kicking in, but I don't thing that's
the case because I'd be seeing more issues than just redrawing. I have not had
this problem in the past when I used Doom, but now that I'm using my own config
it is pretty much guaranteed to occur at some point. I might consider moving
back to Doom, but I really like my config (well, besides this problem), emacs
feels much snappier and more responsive without Doom. Maybe when Doom gets the
3.0 update I will think about moving back.
