:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2022-08-04 Thu>
:MODIFIED: <2022-09-07 Wed 17:11>
:TYPE: note
:END:
#+TITLE: Reading List

* Books
** Nonfiction
*** READ Bound Away: Virginia and the Westward Movement
*** READ Behold A Pale Horse
*** READ Albion's Seed
** Fiction
*** DONE Dreadgod :ARCHIVE:
:PROPERTIES:
:AUTHOR:   Will Wight
:ADDED:    [2022-08-04]
:GOODREADS: https://www.goodreads.com/book/show/59515764-dreadgod?from_search=true&from_srp=true&qid=F1l9gV5TRb&rank=1
:RATING:   :star::star::star::star::star:
:END:
- State "DONE"       from "READ"       [2022-08-15 Mon 15:03] \\
  This might be one of the best of the series yet. I felt like the hero-getting-OP-so-we-need-a-new-and-more-OP-bad-guy-so-the-hero-has-a-reason-to-get-even-more-OP trope was handled well in this books. I am not sure what Will did differently with this book to mitigate that, but it seems to have worked, and another friend of mine agree, so I'm not alone at least! I shed a tear at the end of the book when I read "Lindon's story ends in the next book".
*** DONE The Dread Wyrm :ARCHIVE:
CLOSED: [2023-08-22 Tue 16:09]
:PROPERTIES:
:AUTHOR:   Miles Cameron
:ADDED:    [2022-08-04]
:GOODREADS: https://www.goodreads.com/book/show/23129080-the-dread-wyrm
:END:
- State "DONE"       from "READING"    [2023-08-22 Tue 16:09] \\
  great book!
*** DONE The Fell Sword :ARCHIVE:
CLOSED: [2022-09-07 Wed 17:09]
:PROPERTIES:
:AUTHOR:   Miles Cameron
:ADDED:    [2022-08-04]
:GOODREADS: https://www.goodreads.com/book/show/17737893-the-fell-sword
:END:
*** DONE The Red Knight :ARCHIVE:
:PROPERTIES:
:AUTHOR:   Miles Cameron
:ADDED:    [2022-08-04]
:GOODREADS: https://www.goodreads.com/book/show/13616278-the-red-knight
:ISBN: 9780575113299
:RATING:   :star::star::star::star:
:END:
- State "DONE"       from "READ"       [2022-08-15 Mon 15:03] \\
  I really enjoyed this book. The setting is familiar enough -- England, or as the author refers to it Alba. The magic system in this book is also intersting and different enough to feel like it's not the same old tropes again. There are a LOT of characters though and the switching between them gets annoying once in a while, but generally it's not as bad as other reviews I have read make it out to be.

  One thing I am very interested in seeing is how the redemption arc of the main character -- The Red Knight -- will play out through the series. Without getting into more spoilers than needed, I think the author seems to be setting him up for a coming-to-faith moment in a future book. Throughout the book you see a character who blatantly curses God, but the level of derision and loathing he expresses softens as his time among a convent of nuns goes on.

  Regardless of how the redemption arc plays out, I really appreciate the level of detail that the author put into the "feel" of this book's setting. The use very specfic and archiac spellings of words really helps you feel like this is a middle-age Europe. I'm also always intrigued by books that approach a historical setting and seek to alter it in drastic ways and I like trying to pick out the _actually_ historic elements behind the story. For example, there is a not-to-distant "Empire" which is across the water from Alba. As best I can tell this is either the Holy Roman Empire or the French empire, but right now I can't be certain which.

  Another interesting aspect I like is that the "bad" guys aren't so bad. And it's not because they're "grey" but because the "good" guys are misinformed. I appreciate that the author has taken some level of effort to show that the religious elements in the book openly acknowledge that the "bad" guys aren't all "bad", it makes reading the series a lot easier when there aren't underlying digs like that.

  All in all, I would definitley recommend this book and I will definitely be reading the sequels once I get through Dreadgod!
