:PROPERTIES:
:AUTHOR: Ian S. Pringle

:CREATED:<2023-08-29 Tue>
:CREATED:<2023-08-29 Tue>
:TYPE: page
:END:
#+title: Uses This
* Uses This

There is a sort of common page that some blogs and personal sites have called
"uses-this", which is effectively a list of things the site owner uses. I
thought I'd do the same, it's sort of interesting. I believe, but am not
certain, that it originates with the [[https://usesthis.com][uses-this]] website which is a collection of
interviews with various experts in various fields. This page should be
considered a perpetual work-in-progress, I'll update or add to it over time as I
think of thing things I use or as things I use change.

So, without further ado...

** Office

My office is where I work, both my day-job and any computer related personal
work.

Hardware-wise I use:
 - 2001 MacBook Pro M1 w/ 32 GB RAM. Not much to say here really, I don't have a
   personal computer I use too much, I just use whatever laptop work gives me. I
   did have, technically still do have it, a Thinkpad but it died.
 - ErgoDox EZ keyboard. I am currently using my ErgoDox as if it were a Corne
   v3, so 6x3 with three keys per thumb cluster. I might change this up but for
   the time I'm happy. I use homerow mods and a number of layers.
 - CST 2145 trackball mouse. This has the option to add two extra buttons but I
   have not added them, so just the three button default config.
 - I'm not going to list both monitors. One is an old Dell I use in portrait
   mode and the other is a widescreen LG. Nothing fancy, both just work issued
   items.

Software-wise I use:
 - Emacs for my editor
 - Firefox for my browser, with the Bitwarden and uBlock
   Origin extensions.
 - Wezterm for my terminal
 - Gimp for editing images

That's really about it for software. Emacs is basically an OS, so most things
are in Emacs. I use Slack, Discord, Teams, but I'm not sure those really ought
to even count...


