:PROPERTIES:
:TYPE: slip
:ID:       dc706128-9e40-481b-804e-53ee4bf75183
:END:
#+title: food
#+date: <2022-08-04 Thu>
Food is an interesting topic. I think it is safe to say that modern humans do
not have the right frame of mind when it comes to food. For most of existence
food was not ubiquitous and I think that how we are designed reflects that a
limited food supply is a good thing. A diet should take this into consideration
and artificially (if need be) limit food consumption through regular fasting.

The Bible clearly shows that plant-based foods are good. But after the Fall we
see that meat is also "on the table". Biologically we can see that humans
require meat to thrive, there is something which happened that removed our
ability to survive on plants alone. Any diet must incorporate both meats and
plants.

For most of time humans would have relied on the food currently in season, plus
the grains they'd stored, and meat they'd preserved or had recently killed. I
suspect that a diet that emphasizes traditionally preserved foods, fresh foods,
and grains, is an adequate diet for most people.

Ideally this diet would also be made up of foods that are not from just
anywhere, but rather are locally produced and gathered. The best foods are the
ones grown at home or foraged locally, but foods grown by local farms are also
good. Focusing on local foods will almost entirely eliminate the problems of
GMOs, pesticides, herbicides, deficient soils, and other problems with
mass-grown grocery store foods.
