:PROPERTIES:
:TYPE: slip
:ID:       e1a06552-0ed0-4320-a955-a1610f5a0382
:END:
#+title: grok
#+date: <2022-08-04 Thu>

# grok
/ˈɡrɒk/, /grohk/, transitive verb

#+BEGIN_QUOTE
1. To understand profoundly through intuition or empathy
2. To have or to have acquired an intuitive understanding of; to know (something) without having to think
3. To get the meaning of something
#+END_QUOTE

"Grok" is a neologism coined in the book _Stranger in a Strange Land_ by Robert A. Heinlein. I've never read the book, the term is ingrained enough into the world of software that I'm confident most people who use the term have never even heard of the book or know the word's origins.

More importantly and more applicable to this minute corner of the internet,
"grok" is the name of my "knowledge-base" or "digital garden". And this file is
the jumping off point into the world.  While I don't intend every inkling or
scrape I create to link back to this page, I do endeavor to ensure that this
file is the central hub of my [[file:loci.org][loci]].

Here are a few good jumping off points:
- [[file:christianity.org][Christianity]]
- [[file:technology.org][Technology]]
- [[file:diy.org][DIY]]
- [[file:farming.org][Farming]]

To be on the safe side, there is also the [[./][index]] of all notes, just in case
something slips through the cracks.
