:PROPERTIES:
:TYPE: slip
:ID:       821d939d-962f-45e5-8bfe-e2aec9d46d93
:END:
#+title: list-style-image
#+date: <2023-08-22 Tue 05:30>
#+filetags: :css:

The CSS property ~list-style-image~ takes a URL to an image, or an image-like CSS
object (i.e. ~linear-gradient~) and uses that as the list element's
"bullet-style". This is great if you want to create a custom bullet for your
lists. Sadly this property does not have the detail of other properties, like
the cursor, which can not only take an image, but can take some information
about the image, such as where to align the mid-point to, or how to scale the
image up or down. The image you provide this property must be exactly the right
image without any transformations. The two big things are sizing and then
alignment. Sizing is pretty self-explanatory and you can pull that off with
either software or an API. The alignment is a bit harder. You see the midpoint
of the image's Y-axis is aligned with the start of the list's ~innerHTML~. This
means if your image is not aligned right it will appear askew. If the desired
midpoint of your image is not at the middle of the Y-axis then you will need to
pad the image at the top or bottom.

To easily facilitate this, I've written the small tool below which will let you
select the midpoint of your image and then upon clicking it will correctly pad
the image. Only after I'd created this tool did I find out that ~li~ suck and you
should jsut use a ~::before~ pseudo-element for the custom bullets or use a
~background~ with ~no-repeat~. I will keep my little utility here though as it might
be useful...


#+begin_export html
<script>
const S = {};

function loadImage() {
    if (typeof window.FileReader !== 'function') {
        alert("The file API isn't supported on this browser yet.");
        return;
    }

    let input = document.getElementById('imgfile');
    if (!input) {
        alert("Um, couldn't find the imgfile element.");
    }
    else if (!input.files) {
        alert("This browser doesn't seem to support the `files` property of file inputs.");
    }
    else if (!input.files[0]) {
        alert("Please select a file before clicking 'Load'");
    }
    else {
        let file = input.files[0];
        let fr = new FileReader();
        fr.onload = () => {
            S.img = new Image();
            S.img.onload = init;
            S.img.src = fr.result;
        }
        fr.readAsDataURL(file);
    }
}

function init() {
    S.canvas = document.getElementById("canvas")
    S.ctx = S.canvas.getContext("2d");

    S.ctx.clearRect(0, 0, canvas.width, canvas.height);
    S.width = S.img.width;
    S.height = S.img.height;
    S.canvas.width = S.width;
    S.canvas.height = S.height;

    S.clicked = false;
    S.imgStartY = 0;
    S.imgEndY = S.height

    window.addEventListener("mousemove", e => {
        const rect = S.canvas.getBoundingClientRect();
        const scaleX = S.canvas.width / rect.width;
        const scaleY = S.canvas.height / rect.height;
        S.mouseX = (e.clientX - rect.left) * scaleX;
        S.mouseY = (e.clientY - rect.top) * scaleY;
    }, true);
    window.addEventListener("click", () => { S.clicked = !S.clicked }, true);
    window.requestAnimationFrame(loop);
}

function loop() {
    clear();
    draw();
    window.requestAnimationFrame(loop);
}

function draw() {
    if (!S.clicked) {
        S.canvas.height = S.height;
        S.imgStartY = 0;

        S.lineY = S.mouseY

        S.ctx.drawImage(S.img,0, S.imgStartY, S.width, S.imgEndY);

        S.ctx.beginPath();
        S.ctx.moveTo(0, S.lineY);
        S.ctx.lineTo(S.canvas.width, S.lineY);
        S.ctx.strokeStyle = "#000";
        S.ctx.stroke();
        updateP();
    } else if (S.clicked) {
        var padding;
        if (S.lineY < (S.height / 2)) {
            padding = S.height - S.lineY * 2;
            S.imgStartY = padding;
        } else {
            padding = S.lineY;
            S.imgStartY = 0;
        }
        S.canvas.height = S.height + padding;
        S.ctx.drawImage(S.img,0, S.imgStartY, S.width, S.imgEndY);
    }
    updateUL();
}

function clear() {
    S.ctx.clearRect(0, 0, S.canvas.width, S.canvas.height)
}

function updateP() {
    document.getElementById("yPos").innerText = `Y Position: ${S.lineY}`;
}

function updateUL() {
    document.getElementById("example").style.listStyleImage = `url(${S.canvas.toDataURL()})`;
}
</script>
<form action='#' onsubmit="return false;">
    <input type='file' id='imgfile' />
    <input type='button' id='btnLoad' value='Load' onclick='loadImage();' />
    <p id="yPos"></p>
</form>
<canvas id="canvas" style="border:solid black;"></canvas>
<p id="datauri></p>
<ul id="example">
    <li><div><p>Foo</p></div></li>
    <li><div><p>Bar</p></div></li>
    <li><div><p>Baz</p></div></li>
</ul>
#+end_export
