:PROPERTIES:
:TYPE: slip
:ID:       31cc2c4c-36be-4356-b26f-34361280c342
:END:
#+title:      Particular Baptists
#+date:       [2023-08-25 Fri 06:30]
#+filetags:   :theology:
#+identifier: 20230825T063000

* Particular Baptist

** The Baptist Flavor of the Week

Particular baptists are not so called because they are fastidious (though they
may be so), rather the term particular refers to the doctrines of particular
atonement (commonly called "limited atonement"). The name "particular baptist"
makes most sense when you realize that the opposite would be a "general
baptist", or someone who holds to a general or unlimited atonement. The term is
synonymous with "reformed baptist" and to some lesser extent "calvinistic
baptists".

** Reformed Or Calvinisitc

To many there is little distinction between the terms "reformed" and
"calvinistic". Largely, but not entirely, the distinction is going to be a
historic one. The "reformed" baptist will generally view their theology as
coming from the heritage of John Smyth and would affirm some historic, baptistic
confession. Speaking generally, a "calvinistic baptist" is going to be one who
affirms the points of calvinism, but likely is not confessional and probably is
happy to associate with modern Baptist history, viewing themselves as having
developed their calvinistic theology within the context of the wide-spread
general baptist context of modern American Christianity.
