:PROPERTIES:
:TYPE: slip
:ID:       ec85ec62-9669-4684-870d-fd67184bab91
:END:
#+title:      What to ask when interviewing for a job
#+date: [2023-08-25 Fri 14:40]
#+filetags:   

You know how at the end of a job interview they ask you, "do you have any
questions for us?" and you feel like you gotta ask a question or else they'll
think you're an uninterested candidate, but you have no idea what sort of
questions to ask because you're just looking to make money? Well, these are
questions to ask when you are interviewing for a job.

* Personal
- [ ] Why do you love ${place}?
- [ ] What’s the most important book you’ve read in your career?
- [ ] What about my resume/cover letter/application made me stand out? Or if you
  prefer, what unique things about me or my experience stand out as a good fit
  to you? [Feel this one out. If you can, look at it and ask it as an
  opportunity to improve your strengths and fortify your weaknesses]
- [ ] What makes you most proud of your time working here?
* Role-Specific
- [ ] Front-end stack? I really love React… [This could be any other question
  about tools. Asking about tools you like helps both you and the interviewer
  know if you’re a good fit for one another.]
- [ ] Too early to ask about salary? What range do you have in mind?
- [ ] More tools/day-in-the-life questions. Will depend on role.
* Culture
- [ ] If there’s one thing you could change about your work/team, what would it be?
- [ ] I see ${oneOrTwoThings} are part of your core values. What does it look
  like when someone ${example of what it might look like to fail to meet those
  values}?
- [ ] What about when someone crushes it, or exudes these values?
- [ ] What’s one attribute or characteristic outside of hard/role-based skills
  that this person should have to succeed?
- [ ] After work, how much energy do you have for leisure activities, friends
  and family?
- [ ] Pick one or two from here:
  - [ ] Tell me about a time a team member changed your mind?
  - [ ] Tell me about someone you are proud of.
  - [ ] Do you fully disconnect during holidays and vacations?
  - [ ] Describe a recent success or win.
  - [ ] Tell me about a disagreement or conflict on the team.
  - [ ] How did you start your last team meeting?
  - [ ] What is your ideal person for this role?
  - [ ] Who have you promoted and why?
  - [ ] Tell me about the last person you recognized.
  - [ ] How do you focus on your own growth and development?
* Company
- [ ] Conferences/events? How does ${place} invest in individual career and
  knowledge development?
- [ ] Is ${place} currently a profitable company? If not, what factors play into
  the lack of profitability? [a company being profitable is a good indication
  that it’s a good place to work. Conversely, simply because someplace is not
  profitable does not mean it’s someplace you should avoid… but it’s definitely
  a red flag. Trust me. I’ve been there]
