:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2022-08-04 Thu>
:MODIFIED: <2022-08-04 Thu>
:TYPE: root
:END:
#+title: Index

I'm a sinner saved by grace. I am a husband and father. At work I wear a number of tech related hates; site reliability engineer, systems engineer, software developer, and systems architect. My wife and I also own a 125 acre homestead, which means I am also a farmer, a rancher, a lumberjack, a mechanic, and a few other things depending on what's broken at the moment.

I've sort of stumbled and tripped my way into the software world. I actually am something of a Luddite, I really don't like modern technology all that much. I drive old vehicles, I use old tractors, I don't own or have any desire to own a television, the music we play comes from tapes and CDs, I prefer almost any handtool to the mechanized alternative.

My interests are many and varied, and I hope this site can be some form of outlet for all of them.

You can find my latest [[./blog/][blog posts here]]. I also have a "digital garden" or "knowledge base" that I call "[[./grok/grok.org][grok]]" which might be of interest to some people. I'm not the best "digital gardener" so my notes are a mix of too much information and far too little information! I'm also trying to [[./book][review books]] that I read, just to sort of keep a record of what I'm reading and anything I thought about the book after finishing it.
