:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2023-08-10 Thu 05:35>
:MODIFIED: <2023-08-10 Thu 05:35>
:TYPE: blog
:DRAFT: t
:END:
#+title: A Simple, Random Maze Generator
#+filetags:

#+begin_export html
<script>
function addJitteryBezier(ctx, fromX, fromY, toX, toY) {
 var diffX = toX - fromX;
 var diffY = toY - fromY;

 var neg = Math.random()*diffY/5; // so the x value can go positive or negative from the typical


 ctx.bezierCurveTo(
 -neg + fromX + 2*(Math.random()*diffY/8), fromY + .3*diffY,
 -neg + fromX + 2*(Math.random()*diffY/8), fromY + .6*diffY,
 toX, toY
 );
}
function yLine(ctx, x, startY, endY, interval = 50) {
    ctx.moveTo(x, startY);
    for (let y = startY; y < endY; y += interval){
        addJitteryBezier(ctx, x, y, x, y+interval);
        y+=  interval;
    }
    ctx.stroke();
}

function grid(ctx, startX, startY, endX, endY, cellsX, cellsY) {
    const interval = 50;
    const size = Math.min((endX - startX) / cellsX, (endY - startY) / cellsY);
j
    yLine(ctx, startX, startY, endY)

}
</script>
#+end_export

My wife bought me /Mazes For Programmers/ last Christmas. I was really excited to
read it and then life got in the way and it's sat on my desk (along with /The
Pragmatic Programmer/ which she got me and /The Phoenix Project/ which my boss got
me). I've finally decided to try and get through it during my morning
personal-project time and thought I'd try blogging my way through it.

While I really ought to use Ruby for this, since the book does and learning a
new language is never a bad idea, I think I'm just going to use JavaScript
instead. And, in keeping with not doing things the right way, instead of doing
chapter one by hand, I'm going to do it with a ~<canvas>~ element.

The book starts with the simplest method of creating a maze; make a grid.
#+begin_export html
<canvas id="fig1" style="aspect-ratio:1/1;width:50%;"></canvas>
<script>
const S = {}
function init() {
    S.canvas = document.getElementById("fig1");

    S.canvas.width = S.canvas.offsetWidth;
    S.canvas.height = S.canvas.offsetHeight;
    S.width = S.canvas.width;
    S.height = S.canvas.height;

    S.ctx = S.canvas.getContext('2d');
    S.ctx.translate(0.5, 0.5);

    window.requestAnimationFrame(draw)
}

function draw() {
    grid(S.ctx, 10, 10, S.width - 20, S.height - 20, 4, 4);
}
window.addEventListener('load', init)
</script>
#+end_export
