:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2024-02-01 Thu 12:38>
:MODIFIED: <2024-02-02 Fri 10:07>
:TYPE: blog
:END:
#+title: Gastrosophy, a Philosophy of Food
#+filetags: :food:

I've been working on a "philosophy of food" sort of thing for a few years and
trying to really get at something that's "natural" and maybe is a common
rule/concept among most people in the world historically. Basically the idea of
fresh, whole foods or naturally preserved foods, interspersed with fasts between
a day and maybe half a week.

I'v also been thinking through the idea of seasonal diets. You eat
fresh fruits and vegetables in the summer and fall. In the spring lots of
greens, shoots, sprouts, etc. Spring through Fall there would be a focus on eggs
and fish for protein. In the fall and winter you'd eat high starch roots,
fermented/cured foods, and meat. Probably would have most of the fasting in the
late winter and early spring.

Obviously this doesn't apply to all peoples at all times. Inuits have
historically subsisted on animal alone. Plenty of others have done the same on
fruits or vegetables. The historic Swiss diet was almost exclusively dairy for
months on end. So the body is capable of adapting to anything, but I think there
are some major hinderances in today's diets and I think it's sort of funny that
we even have to think about our foods today when even 75 to 100 years ago you
didn't think about your diet, you just ate.

I believe that the mass overeating problem could very well be related to the
fact that people are consuming nutritionless foods. Your body signals a need to
eat for two reasons primarily, hunger and nutrient needs. If you're body signals
a need for nutrients but your foods are lacking in nutrients, you'll eat and
still be hungry. This is why the two extremes of diets work pretty well for
people. It's hard to eat only animal products and lack nutrients. Likewise, it's
hard to eat strictly plants and lack nutrients. The problem is in the
modern-middle where you can consume things that are tantamount to calorically
dense air.

The nutrient density problem is partially a problem with the preparation of
modern foods. Many foods are heated to such a heat that it destroys the
nutrients which are present in it. This is a known problem with dog food, it can
last forever but has virtually no micronutrients left because of how it is
preserved with heat treatment. The same is true for human foods as well. While I
have no evidence of it, I wonder if the preparation of our processed foods
contributes to other issues, such as gluten problems. Another friend of mine had
said that his family could consume fermented wheat but not unfermented wheat,
which is another preparation difference that pervades modern baking.

I'm reading Omnivore's Dilemma and then will follow that up with In Defense of
Food. I've been told both books, by Michael Pollan, trace similar trains of
thought on food as what I have discussed. I'm interested to see what his take on
it is.
