:PROPERTIES:
:AUTHOR: Ian S. Pringle
:CREATED: <2023-08-27 Sun 15:25>
:MODIFIED: <2023-08-27 Sun 15:25>
:TYPE: blog
:END:
#+title: To Start a Weekly Linklog
#+filetags: :meta:

I thought it might be interested in starting a [[https://en.wikipedia.org/wiki/Linklog][Linklog]], not so much in the vein
of true 90s and early 00s blogging such as [[https://dotat.at/:/][Tony Finch's own linklog]], but
something more of a facsimile to [[https://pig-monkey.com/tag/links/][Peter Hogg's]], which is to say weekly or
monthly, and occasionally with commentary. I've been using a bookmarking service
called "[[https://raindrop.io/][Raindrop]]" and I use it pretty extensively in order to keep the number of
tabs I have open to a minimum. About once per week I try to organize and sort
the links I've bookmarked on Raindrop, and I thought I could export them to here
as well. I like to think I find some fairly interesting websites now and then.

I shall endeavor to start my effort tomorrow, cleaning out the last week-ish
(since the 23rd really) of new, unsorted bookmarks, and sharing them here.
Raindrop actually has a pretty robust API, as I understand, and it might be that
I can automate a large portion of the linklog post creation!
