name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Remove files marked :PRIVATE: t"
        run: 'find ./content -type f -exec grep -q "^:PRIVATE: t\$" {} \; -delete'

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=org dist
